[package]
name = "gpuz_term"
version = "0.0.2"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
# gpui bandled inside zed repo
gpui = { git = "https://github.com/zed-industries/zed", rev = "397cbc84de333eeb56849dc90782d365b37e60d7" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "397cbc84de333eeb56849dc90782d365b37e60d7", features = ["wayland", "x11", "font-kit"] }
alacritty_terminal = { git = "https://github.com/zed-industries/alacritty", rev = "4c129667ce56611becdc82de6e28218c80e2e88f" }
anyhow = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json_lenient = "0.2"

[dev-dependencies]
# test platform for rendering views without a display
gpui = { git = "https://github.com/zed-industries/zed", rev = "397cbc84de333eeb56849dc90782d365b37e60d7", features = ["test-support"] }
